// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mamecast_joydev.proto

#include "mamecast_joydev.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace mamecast {
class Gamepad_UpdateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Gamepad_Update> _instance;
} _Gamepad_Update_default_instance_;
}  // namespace mamecast
static void InitDefaultsscc_info_Gamepad_Update_mamecast_5fjoydev_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mamecast::_Gamepad_Update_default_instance_;
    new (ptr) ::mamecast::Gamepad_Update();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mamecast::Gamepad_Update::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Gamepad_Update_mamecast_5fjoydev_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Gamepad_Update_mamecast_5fjoydev_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mamecast_5fjoydev_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mamecast_5fjoydev_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mamecast_5fjoydev_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_mamecast_5fjoydev_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mamecast::Gamepad_Update, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mamecast::Gamepad_Update, joy_id_),
  PROTOBUF_FIELD_OFFSET(::mamecast::Gamepad_Update, buttons_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mamecast::Gamepad_Update)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mamecast::_Gamepad_Update_default_instance_),
};

const char descriptor_table_protodef_mamecast_5fjoydev_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025mamecast_joydev.proto\022\010mamecast\"1\n\016Gam"
  "epad_Update\022\016\n\006joy_id\030\001 \001(\r\022\017\n\007buttons\030\002"
  " \001(\014b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mamecast_5fjoydev_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_mamecast_5fjoydev_2eproto_sccs[1] = {
  &scc_info_Gamepad_Update_mamecast_5fjoydev_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mamecast_5fjoydev_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mamecast_5fjoydev_2eproto = {
  false, false, descriptor_table_protodef_mamecast_5fjoydev_2eproto, "mamecast_joydev.proto", 92,
  &descriptor_table_mamecast_5fjoydev_2eproto_once, descriptor_table_mamecast_5fjoydev_2eproto_sccs, descriptor_table_mamecast_5fjoydev_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_mamecast_5fjoydev_2eproto::offsets,
  file_level_metadata_mamecast_5fjoydev_2eproto, 1, file_level_enum_descriptors_mamecast_5fjoydev_2eproto, file_level_service_descriptors_mamecast_5fjoydev_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_mamecast_5fjoydev_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_mamecast_5fjoydev_2eproto)), true);
namespace mamecast {

// ===================================================================

void Gamepad_Update::InitAsDefaultInstance() {
}
class Gamepad_Update::_Internal {
 public:
};

Gamepad_Update::Gamepad_Update(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mamecast.Gamepad_Update)
}
Gamepad_Update::Gamepad_Update(const Gamepad_Update& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  buttons_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_buttons().empty()) {
    buttons_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_buttons(),
      GetArena());
  }
  joy_id_ = from.joy_id_;
  // @@protoc_insertion_point(copy_constructor:mamecast.Gamepad_Update)
}

void Gamepad_Update::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Gamepad_Update_mamecast_5fjoydev_2eproto.base);
  buttons_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  joy_id_ = 0u;
}

Gamepad_Update::~Gamepad_Update() {
  // @@protoc_insertion_point(destructor:mamecast.Gamepad_Update)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Gamepad_Update::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  buttons_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Gamepad_Update::ArenaDtor(void* object) {
  Gamepad_Update* _this = reinterpret_cast< Gamepad_Update* >(object);
  (void)_this;
}
void Gamepad_Update::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Gamepad_Update::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Gamepad_Update& Gamepad_Update::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Gamepad_Update_mamecast_5fjoydev_2eproto.base);
  return *internal_default_instance();
}


void Gamepad_Update::Clear() {
// @@protoc_insertion_point(message_clear_start:mamecast.Gamepad_Update)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  buttons_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  joy_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Gamepad_Update::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 joy_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          joy_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes buttons = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_buttons();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Gamepad_Update::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mamecast.Gamepad_Update)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 joy_id = 1;
  if (this->joy_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_joy_id(), target);
  }

  // bytes buttons = 2;
  if (this->buttons().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_buttons(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mamecast.Gamepad_Update)
  return target;
}

size_t Gamepad_Update::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mamecast.Gamepad_Update)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes buttons = 2;
  if (this->buttons().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_buttons());
  }

  // uint32 joy_id = 1;
  if (this->joy_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_joy_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Gamepad_Update::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mamecast.Gamepad_Update)
  GOOGLE_DCHECK_NE(&from, this);
  const Gamepad_Update* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Gamepad_Update>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mamecast.Gamepad_Update)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mamecast.Gamepad_Update)
    MergeFrom(*source);
  }
}

void Gamepad_Update::MergeFrom(const Gamepad_Update& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mamecast.Gamepad_Update)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.buttons().size() > 0) {
    _internal_set_buttons(from._internal_buttons());
  }
  if (from.joy_id() != 0) {
    _internal_set_joy_id(from._internal_joy_id());
  }
}

void Gamepad_Update::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mamecast.Gamepad_Update)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Gamepad_Update::CopyFrom(const Gamepad_Update& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mamecast.Gamepad_Update)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Gamepad_Update::IsInitialized() const {
  return true;
}

void Gamepad_Update::InternalSwap(Gamepad_Update* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  buttons_.Swap(&other->buttons_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(joy_id_, other->joy_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Gamepad_Update::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mamecast
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mamecast::Gamepad_Update* Arena::CreateMaybeMessage< ::mamecast::Gamepad_Update >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mamecast::Gamepad_Update >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
