// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mamecast_joydev.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mamecast_5fjoydev_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mamecast_5fjoydev_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mamecast_5fjoydev_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mamecast_5fjoydev_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mamecast_5fjoydev_2eproto;
namespace mamecast {
class Gamepad_Update;
class Gamepad_UpdateDefaultTypeInternal;
extern Gamepad_UpdateDefaultTypeInternal _Gamepad_Update_default_instance_;
}  // namespace mamecast
PROTOBUF_NAMESPACE_OPEN
template<> ::mamecast::Gamepad_Update* Arena::CreateMaybeMessage<::mamecast::Gamepad_Update>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mamecast {

// ===================================================================

class Gamepad_Update PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mamecast.Gamepad_Update) */ {
 public:
  inline Gamepad_Update() : Gamepad_Update(nullptr) {};
  virtual ~Gamepad_Update();

  Gamepad_Update(const Gamepad_Update& from);
  Gamepad_Update(Gamepad_Update&& from) noexcept
    : Gamepad_Update() {
    *this = ::std::move(from);
  }

  inline Gamepad_Update& operator=(const Gamepad_Update& from) {
    CopyFrom(from);
    return *this;
  }
  inline Gamepad_Update& operator=(Gamepad_Update&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Gamepad_Update& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Gamepad_Update* internal_default_instance() {
    return reinterpret_cast<const Gamepad_Update*>(
               &_Gamepad_Update_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Gamepad_Update& a, Gamepad_Update& b) {
    a.Swap(&b);
  }
  inline void Swap(Gamepad_Update* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Gamepad_Update* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Gamepad_Update* New() const final {
    return CreateMaybeMessage<Gamepad_Update>(nullptr);
  }

  Gamepad_Update* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Gamepad_Update>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Gamepad_Update& from);
  void MergeFrom(const Gamepad_Update& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Gamepad_Update* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mamecast.Gamepad_Update";
  }
  protected:
  explicit Gamepad_Update(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mamecast_5fjoydev_2eproto);
    return ::descriptor_table_mamecast_5fjoydev_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kButtonsFieldNumber = 2,
    kJoyIdFieldNumber = 1,
  };
  // bytes buttons = 2;
  void clear_buttons();
  const std::string& buttons() const;
  void set_buttons(const std::string& value);
  void set_buttons(std::string&& value);
  void set_buttons(const char* value);
  void set_buttons(const void* value, size_t size);
  std::string* mutable_buttons();
  std::string* release_buttons();
  void set_allocated_buttons(std::string* buttons);
  private:
  const std::string& _internal_buttons() const;
  void _internal_set_buttons(const std::string& value);
  std::string* _internal_mutable_buttons();
  public:

  // uint32 joy_id = 1;
  void clear_joy_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 joy_id() const;
  void set_joy_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_joy_id() const;
  void _internal_set_joy_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:mamecast.Gamepad_Update)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr buttons_;
  ::PROTOBUF_NAMESPACE_ID::uint32 joy_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mamecast_5fjoydev_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Gamepad_Update

// uint32 joy_id = 1;
inline void Gamepad_Update::clear_joy_id() {
  joy_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Gamepad_Update::_internal_joy_id() const {
  return joy_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Gamepad_Update::joy_id() const {
  // @@protoc_insertion_point(field_get:mamecast.Gamepad_Update.joy_id)
  return _internal_joy_id();
}
inline void Gamepad_Update::_internal_set_joy_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  joy_id_ = value;
}
inline void Gamepad_Update::set_joy_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_joy_id(value);
  // @@protoc_insertion_point(field_set:mamecast.Gamepad_Update.joy_id)
}

// bytes buttons = 2;
inline void Gamepad_Update::clear_buttons() {
  buttons_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Gamepad_Update::buttons() const {
  // @@protoc_insertion_point(field_get:mamecast.Gamepad_Update.buttons)
  return _internal_buttons();
}
inline void Gamepad_Update::set_buttons(const std::string& value) {
  _internal_set_buttons(value);
  // @@protoc_insertion_point(field_set:mamecast.Gamepad_Update.buttons)
}
inline std::string* Gamepad_Update::mutable_buttons() {
  // @@protoc_insertion_point(field_mutable:mamecast.Gamepad_Update.buttons)
  return _internal_mutable_buttons();
}
inline const std::string& Gamepad_Update::_internal_buttons() const {
  return buttons_.Get();
}
inline void Gamepad_Update::_internal_set_buttons(const std::string& value) {
  
  buttons_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Gamepad_Update::set_buttons(std::string&& value) {
  
  buttons_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:mamecast.Gamepad_Update.buttons)
}
inline void Gamepad_Update::set_buttons(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  buttons_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:mamecast.Gamepad_Update.buttons)
}
inline void Gamepad_Update::set_buttons(const void* value,
    size_t size) {
  
  buttons_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:mamecast.Gamepad_Update.buttons)
}
inline std::string* Gamepad_Update::_internal_mutable_buttons() {
  
  return buttons_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Gamepad_Update::release_buttons() {
  // @@protoc_insertion_point(field_release:mamecast.Gamepad_Update.buttons)
  return buttons_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Gamepad_Update::set_allocated_buttons(std::string* buttons) {
  if (buttons != nullptr) {
    
  } else {
    
  }
  buttons_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), buttons,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:mamecast.Gamepad_Update.buttons)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mamecast

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mamecast_5fjoydev_2eproto
